(*
$Id: annotated_3d_model_equivalence_criteria_schema.exp,v 1.5 2018/04/04 04:35:26 ftanaka Exp $
ISO 10303 TC184/SC4/WG12 N9998

EXPRESS Source:
ISO 10303-62 ed1 Equivalence validation of product data - Annotated 3d model equivalence criteria schema

The following permission notice and disclaimer shall be included in all copies of this EXPRESS schema ("the Schema"), 
and derivations of the Schema:

Copyright ISO 2014  All rights reserved
Permission is hereby granted, free of charge in perpetuity, to any person obtaining a copy of the Schema,
to use, copy, modify, merge and distribute free of charge, copies of the Schema for the purposes of developing, 
implementing, installing and using software based on the Schema, and to permit persons to whom the Schema is furnished to do so, 
subject to the following conditions:

THE SCHEMA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SCHEMA OR THE 
USE OR OTHER DEALINGS IN THE SCHEMA.

In addition, any modified copy of the Schema shall include the following notice:

THIS SCHEMA HAS BEEN MODIFIED FROM THE SCHEMA DEFINED IN
ISO 10303-62 ed1 Equivalence validation of product data - Annotated model 3d equivalence criteria schema
AND SHOULD NOT BE INTERPRETED AS COMPLYING WITH THAT STANDARD
*)

SCHEMA annotated_3d_model_equivalence_criteria_schema '{iso standard 10303 part(62) version(1) object(1) annotated_3d_model_equivalence_criteria_schema(1)}';

  REFERENCE FROM measure_schema
    (measure_with_unit,
     unit);

  REFERENCE FROM product_data_equivalence_criteria_schema
    (data_equivalence_assessment_specification,
     data_equivalence_criteria_representation,
     data_equivalence_criterion,
     data_equivalence_criterion_assessment_association,
     data_equivalence_inspection_requirement,
     data_equivalence_report_request);
   
  REFERENCE FROM product_data_equivalence_inspection_result_schema
    (inspected_equivalence_element_select);

  REFERENCE FROM qualified_measure_schema
    (measure_representation_item,
     qualified_representation_item,
     value_qualifier,
     type_qualifier);

  REFERENCE FROM representation_schema
    (compound_representation_item,
     representation,
     representation_item,
     representation_item_relationship,
     set_representation_item,
     value_representation_item);

  REFERENCE FROM shape_data_quality_criteria_schema
    (shape_measurement_accuracy,
     shape_data_quality_lower_value_limit,
     shape_data_quality_upper_value_limit,
     shape_data_quality_value_limit,
     shape_data_quality_value_limit_type_select,
     shape_data_quality_value_range);

  REFERENCE FROM support_resource_schema 
    (identifier,
     label,
     text,
     bag_to_set);
  
  TYPE a3m_accuracy_type_name = EXTENSIBLE ENUMERATION;
  END_TYPE;
  
  TYPE a3m_detected_difference_type_name = EXTENSIBLE ENUMERATION;
  END_TYPE;

  TYPE a3m_element_type_name = EXTENSIBLE ENUMERATION;
  END_TYPE;

  TYPE a3m_equivalence_assessment_specification_select = SELECT
    (a3m_equivalence_assessment_by_logical_test,
     a3m_equivalence_assessment_by_numerical_test);
  END_TYPE;

  TYPE a3m_measured_data_type_name = EXTENSIBLE ENUMERATION;
  END_TYPE;

  TYPE accuracy_associated_target_select = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE representative_value_type = ENUMERATION OF
    (average_value,
     max_value,
     min_value,
     min_max_value);
  END_TYPE;

  ENTITY a3m_equivalence_accuracy_association;
      id : identifier;
      name : label;
      description : OPTIONAL text;
      specific_accuracy   : shape_measurement_accuracy;
      equivalence_target : accuracy_associated_target_select;
  END_ENTITY;
  
  ENTITY a3m_equivalence_assessment_by_logical_test
    SUBTYPE OF(data_equivalence_assessment_specification);
  END_ENTITY;

  ENTITY a3m_equivalence_assessment_by_numerical_test
    SUBTYPE OF(data_equivalence_assessment_specification);
      threshold : shape_data_quality_value_limit_type_select;
  END_ENTITY;

  ENTITY a3m_equivalence_criteria_representation
    SUBTYPE OF(data_equivalence_criteria_representation);
    WHERE
      WR1 : SIZEOF( QUERY( q <* SELF\representation.items|
                               'ANNOTATED_3D_MODEL_EQUIVALENCE_CRITERIA_SCHEMA.' +
                               'A3M_EQUIVALENCE_CRITERION' IN TYPEOF(q))) > 0;
  END_ENTITY;
  
  ENTITY a3m_equivalence_criterion
    ABSTRACT SUPERTYPE OF (a3m_equivalence_criterion_with_specified_elements)
    SUBTYPE OF(data_equivalence_criterion, data_equivalence_inspection_requirement);
      assessment_specification : a3m_equivalence_assessment_specification_select;
      comparing_element_types : LIST[1:?] OF a3m_element_type_name;
      compared_element_types : LIST[1:?] OF a3m_element_type_name;
      measured_data_type : a3m_measured_data_type_name;
      detected_difference_types : LIST[0:?] OF a3m_detected_difference_type_name;
      accuracy_types : LIST[0:?] OF a3m_accuracy_type_name;
    WHERE
      WR1 : SIZEOF(USEDIN(SELF,
            'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
            'DATA_EQUIVALENCE_CRITERION_ASSESSMENT_ASSOCIATION.'+
            'CRITERION'
            )) = 0;
      WR2 : SIZEOF(QUERY(i1<*bag_to_set(
              USEDIN(SELF,
                    'REPRESENTATION_SCHEMA.'+
                    'REPRESENTATION_ITEM_RELATIONSHIP.'+
                    'RELATED_REPRESENTATION_ITEM'))|
             'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
             'DATA_EQUIVALENCE_CRITERION_INSPECTION_ASSOCIATION'
              IN TYPEOF(i1))) = 0;
      WR3 : SIZEOF(QUERY(i1<*bag_to_set(
              USEDIN(SELF,
                    'REPRESENTATION_SCHEMA.'+
                    'REPRESENTATION_ITEM_RELATIONSHIP.'+
                    'RELATING_REPRESENTATION_ITEM'))|
             'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
             'DATA_EQUIVALENCE_CRITERION_INSPECTION_ASSOCIATION'
              IN TYPEOF(i1))) = 0;
  END_ENTITY;

  ENTITY a3m_equivalence_criterion_with_specified_elements
    SUBTYPE OF(a3m_equivalence_criterion);
      comparing_specified_elements : SET[1:?] OF inspected_equivalence_element_select; 
      compared_specified_elements : SET[1:?] OF inspected_equivalence_element_select; 
  END_ENTITY;

  ENTITY a3m_equivalence_inspection_requirement_with_values
    ABSTRACT SUPERTYPE
    SUBTYPE OF(data_equivalence_inspection_requirement);
      applied_values : SET[1:?] OF measure_representation_item;
  END_ENTITY;

  ENTITY a3m_equivalence_summary_report_request_with_representative_value
    SUBTYPE OF(data_equivalence_report_request);
      report_request_type : representative_value_type;
  END_ENTITY;

END_SCHEMA; -- annotated_3d_model_equivalence_criteria_schema
(*
$Id: annotated_3d_model_equivalence_inspection_result_schema.exp,v 1.6 2018/04/04 04:35:27 ftanaka Exp $
ISO 10303 TC184/SC4/WG12 N9999

EXPRESS Source:
ISO 10303-62 ed1 Equivalence validation of product data - Annotated 3d model equivalence inspection result schema

The following permission notice and disclaimer shall be included in all copies of this EXPRESS schema ("the Schema"), 
and derivations of the Schema:

Copyright ISO 2014  All rights reserved
Permission is hereby granted, free of charge in perpetuity, to any person obtaining a copy of the Schema,
to use, copy, modify, merge and distribute free of charge, copies of the Schema for the purposes of developing, 
implementing, installing and using software based on the Schema, and to permit persons to whom the Schema is furnished to do so, 
subject to the following conditions:

THE SCHEMA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SCHEMA OR THE 
USE OR OTHER DEALINGS IN THE SCHEMA.

In addition, any modified copy of the Schema shall include the following notice:

THIS SCHEMA HAS BEEN MODIFIED FROM THE SCHEMA DEFINED IN
ISO 10303-62 ed1 Equivalence validation of product data - Annotated model 3d equivalence inspection result schema
AND SHOULD NOT BE INTERPRETED AS COMPLYING WITH THAT STANDARD
*)

SCHEMA annotated_3d_model_equivalence_inspection_result_schema '{iso standard 10303 part(62) version(1) object(1) annotated_3d_model_equivalence_inspection_result_schema(1)}';

  REFERENCE FROM annotated_3d_model_equivalence_criteria_schema
    (representative_value_type);

  REFERENCE FROM product_data_equivalence_inspection_result_schema
    (criterion_report_item_with_number_of_instances,
     criterion_report_item_with_value,
     data_equivalence_inspection_result,
     data_equivalence_inspection_result_representation,
     data_equivalence_inspection_criterion_report_item,
     data_equivalence_inspection_instance_report_item);
     
  REFERENCE FROM shape_data_quality_criteria_schema
    (shape_measurement_accuracy);

  TYPE equivalence_detected_difference_select = EXTENSIBLE SELECT;
  END_TYPE;

  TYPE equivalence_measured_value_select = EXTENSIBLE SELECT;
  END_TYPE;
 
  TYPE target_annotated_3d_model_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  ENTITY a3m_equivalence_criterion_report_item_with_measured_value
    SUBTYPE OF(data_equivalence_inspection_criterion_report_item);
      representative_measured_value : equivalence_measured_value_select;
      value_type : representative_value_type;
    UNIQUE
      UR1: SELF\data_equivalence_inspection_criterion_report_item.criterion_report,value_type;
  END_ENTITY;

  ENTITY a3m_equivalence_inspection_instance_report_item
    SUBTYPE OF(data_equivalence_inspection_instance_report_item);
      measured_value_for_inspected_element    :equivalence_measured_value_select;
  END_ENTITY;

  ENTITY a3m_equivalence_inspection_result_representation
    SUBTYPE OF(data_equivalence_inspection_result_representation);
  END_ENTITY;
 
  ENTITY a3m_inspected_model_and_inspection_result_relationship;
     inspected_model   : target_annotated_3d_model_select;
     equivalence_result : a3m_equivalence_inspection_result_representation;
  END_ENTITY;
 
  ENTITY equivalence_instance_report_item_with_notable_instances
    SUBTYPE OF(a3m_equivalence_inspection_instance_report_item);
      notable_instances : LIST [1:?] OF equivalence_notable_instance;
  END_ENTITY;
 
  ENTITY equivalence_notable_instance;
      comparing_elements : LIST [0:?] OF equivalence_detected_difference_select;
      compared_elements  : LIST [0:?] OF equivalence_detected_difference_select;
      measured_value    : equivalence_measured_value_select;
    WHERE
     WR1: (SIZEOF(comparing_elements) <> 0) OR (SIZEOF(compared_elements) <> 0);
  END_ENTITY;

  SUBTYPE_CONSTRAINT a3m_criterion_report_item_subtypes 
              FOR data_equivalence_inspection_criterion_report_item;
    ONEOF (a3m_equivalence_criterion_report_item_with_measured_value,
           criterion_report_item_with_number_of_instances,
           criterion_report_item_with_value);
  END_SUBTYPE_CONSTRAINT;

END_SCHEMA; -- annotated_3d_model_equivalence_inspection_result_schema
(*
$Id: product_data_equivalence_criteria_schema.exp,v 1.6 2018/04/04 04:35:27 ftanaka Exp $
ISO 10303 TC184/SC4/WG12 N9996

EXPRESS Source:
ISO 10303-62 ed1 Equivalence validation of product data - Product data equivalence criteria schema

The following permission notice and disclaimer shall be included in all copies of this EXPRESS schema ("the Schema"), 
and derivations of the Schema:

Copyright ISO 2014  All rights reserved
Permission is hereby granted, free of charge in perpetuity, to any person obtaining a copy of the Schema,
to use, copy, modify, merge and distribute free of charge, copies of the Schema for the purposes of developing, 
implementing, installing and using software based on the Schema, and to permit persons to whom the Schema is furnished to do so, 
subject to the following conditions:

THE SCHEMA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SCHEMA OR THE 
USE OR OTHER DEALINGS IN THE SCHEMA.

In addition, any modified copy of the Schema shall include the following notice:

THIS SCHEMA HAS BEEN MODIFIED FROM THE SCHEMA DEFINED IN
ISO 10303-62 ed1 Equivalence validation of product data - Product data equivalence criteria schema
AND SHOULD NOT BE INTERPRETED AS COMPLYING WITH THAT STANDARD
*)

SCHEMA product_data_equivalence_criteria_schema '{iso standard 10303 part(62) version(1) object(1) product_data_equivalence_criteria_schema(1)}';

  REFERENCE FROM product_data_equivalence_inspection_result_schema
    (data_equivalence_inspection_result_representation);

  REFERENCE FROM representation_schema
    (representation,
     representation_item,
     representation_item_relationship);

  REFERENCE FROM support_resource_schema 
    (identifier,
     label,
     text,
     bag_to_set);

  TYPE detailed_report_style_type = ENUMERATION OF
    (inspected_element,
     defective_element);
  END_TYPE;

  TYPE preferred_report_ordering = ENUMERATION OF
    (in_notable_order,
     in_detected_order);
  END_TYPE;

  TYPE summary_report_style_type = ENUMERATION OF
    (conclusion,
     number_of_defects,
     number_of_inspections);
  END_TYPE;

  ENTITY data_equivalence_assessment_inspection_association;
      assessment_specification : data_equivalence_criterion_assessment_association;
      inspection_requirement  : data_equivalence_criterion_inspection_association;
    WHERE
      WR1 : SELF.inspection_requirement\representation_item_relationship.relating_representation_item
            :=: SELF.assessment_specification.criterion;
  END_ENTITY;

  ENTITY data_equivalence_assessment_specification;
      id : identifier;
      name : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY data_equivalence_criteria_representation
    SUBTYPE OF(representation);
    WHERE
      WR1 :  SIZEOF( QUERY( q <* SELF\representation.items|
                                'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.' +
                                'DATA_EQUIVALENCE_CRITERION' IN TYPEOF(q))) > 0;
  END_ENTITY;

  ENTITY data_equivalence_criterion
    SUBTYPE OF(representation_item);
    WHERE
      WR1 : SIZEOF(QUERY(q <*
              bag_to_set( USEDIN(SELF,
                'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
              |'PRODUCT_DATA_EQUIVALENCE_INSPECTION_RESULT_SCHEMA.'+
               'DATA_EQUIVALENCE_INSPECTION_RESULT_REPRESENTATION'
               IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_criterion_assessment_association;
      criterion                : data_equivalence_criterion;
      assessment_specification : data_equivalence_assessment_specification;
  END_ENTITY;

  ENTITY data_equivalence_criterion_inspection_association
    SUBTYPE OF(representation_item_relationship);
      SELF\representation_item_relationship.relating_representation_item : data_equivalence_criterion;
      SELF\representation_item_relationship.related_representation_item  : data_equivalence_inspection_requirement;
  END_ENTITY;

  ENTITY data_equivalence_inspection_requirement
    SUBTYPE OF(representation_item);
    WHERE
      WR1 : SIZEOF(QUERY(q <*
              bag_to_set( USEDIN(SELF,
                'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
              |'PRODUCT_DATA_EQUIVALENCE_INSPECTION_RESULT_SCHEMA.'+
               'DATA_EQUIVALENCE_INSPECTION_RESULT_REPRESENTATION'
               IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_report_request;
      id : identifier;
      name : label;
      description : OPTIONAL text;
      criterion_of_report_request : data_equivalence_criterion;
  END_ENTITY;

  ENTITY detailed_equivalence_report_request
    SUBTYPE OF(data_equivalence_report_request);
      report_request_type : detailed_report_style_type;
      report_sequence     : preferred_report_ordering;
  END_ENTITY;

  ENTITY detailed_equivalence_report_request_with_number_of_instances
    SUBTYPE OF(detailed_equivalence_report_request);
      number_of_instances : INTEGER;
    DERIVE
      SELF\detailed_equivalence_report_request.report_request_type:detailed_report_style_type := inspected_element;
  END_ENTITY;

  ENTITY summary_report_request_with_number_of_instances
    SUBTYPE OF(data_equivalence_report_request);
      report_request_type : SET [1:3] OF summary_report_style_type;
  END_ENTITY;

END_SCHEMA; -- product_data_equivalence_criteria_schema
(*
$Id: product_data_equivalence_definition_schema.exp,v 1.10 2018/04/04 04:35:26 ftanaka Exp $
ISO 10303 TC184/SC4/WG12 N9995

EXPRESS Source:
ISO 10303-62 ed1 Equivalence validation of product data - Product data equivalence definition schema

The following permission notice and disclaimer shall be included in all copies of this EXPRESS schema ("the Schema"), 
and derivations of the Schema:

Copyright ISO 2014  All rights reserved
Permission is hereby granted, free of charge in perpetuity, to any person obtaining a copy of the Schema,
to use, copy, modify, merge and distribute free of charge, copies of the Schema for the purposes of developing, 
implementing, installing and using software based on the Schema, and to permit persons to whom the Schema is furnished to do so, 
subject to the following conditions:

THE SCHEMA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SCHEMA OR THE 
USE OR OTHER DEALINGS IN THE SCHEMA.

In addition, any modified copy of the Schema shall include the following notice:

THIS SCHEMA HAS BEEN MODIFIED FROM THE SCHEMA DEFINED IN
ISO 10303-62 ed1 Equivalence validation of product data - Product data equivalence definition schema
AND SHOULD NOT BE INTERPRETED AS COMPLYING WITH THAT STANDARD
*)

SCHEMA product_data_equivalence_definition_schema '{iso standard 10303 part(62) version(1) object(1) product_data_equivalence_definition_schema(1)}';

  REFERENCE FROM product_data_equivalence_criteria_schema
    (data_equivalence_criteria_representation);

  REFERENCE FROM product_data_equivalence_inspection_result_schema
    (data_equivalence_inspection_result_representation);
    
  REFERENCE FROM product_definition_schema
    (product_definition_or_reference,
     product_definition_relationship);

  REFERENCE FROM support_resource_schema 
    (identifier,
     label,
     text);

  TYPE equivalence_product_data_select = SELECT
    (product_definition_or_reference,
     product_definition_relationship);
  END_TYPE;

  TYPE used_equivalence_representation_select = SELECT
    (data_equivalence_criteria_representation,
     data_equivalence_inspection_result_representation);
  END_TYPE;

  TYPE validation_criteria_or_results_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;

  ENTITY data_equivalence_definition;
      id : identifier;
      name : label;
      description : OPTIONAL text;
  END_ENTITY;

  ENTITY data_equivalence_definition_relationship;
      id : identifier;
      name : label;
      description : OPTIONAL text;
      relating_data_equivalence_definition : data_equivalence_definition;
      related_data_equivalence_definition  : data_equivalence_definition;
  END_ENTITY;
  
  ENTITY data_equivalence_definition_representation_relationship;
      id : identifier;
      name : label;
      description : OPTIONAL text;
      definition          : data_equivalence_definition;
      used_representation : used_equivalence_representation_select;
  END_ENTITY;
  
  ENTITY product_data_and_data_equivalence_relationship;
      id : identifier;
      name : label;
      description : OPTIONAL text;
      product_data : equivalence_product_data_select;
      data_equivalence : data_equivalence_definition;
  END_ENTITY;
  
  ENTITY validation_software_identification;
      id : identifier;
      name : label;
      description : OPTIONAL text;
      software_name : label;
      additional_name : label;
      validation_criteria_or_results : validation_criteria_or_results_select;
  END_ENTITY;
  

END_SCHEMA; -- product_data_equivalence_definition_schema
(*
$Id: product_data_equivalence_inspection_result_schema.exp,v 1.7 2018/04/04 04:35:27 ftanaka Exp $
ISO 10303 TC184/SC4/WG12 N9997

EXPRESS Source:
ISO 10303-62 ed1 Equivalence validation of product data - Product data equivalence inspection result schema

The following permission notice and disclaimer shall be included in all copies of this EXPRESS schema ("the Schema"), 
and derivations of the Schema:

Copyright ISO 2014  All rights reserved
Permission is hereby granted, free of charge in perpetuity, to any person obtaining a copy of the Schema,
to use, copy, modify, merge and distribute free of charge, copies of the Schema for the purposes of developing, 
implementing, installing and using software based on the Schema, and to permit persons to whom the Schema is furnished to do so, 
subject to the following conditions:

THE SCHEMA IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, 
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SCHEMA OR THE 
USE OR OTHER DEALINGS IN THE SCHEMA.

In addition, any modified copy of the Schema shall include the following notice:

THIS SCHEMA HAS BEEN MODIFIED FROM THE SCHEMA DEFINED IN
ISO 10303-62 ed1 Equivalence validation of product data - Product data equivalence inspection result schema
AND SHOULD NOT BE INTERPRETED AS COMPLYING WITH THAT STANDARD
*)

SCHEMA product_data_equivalence_inspection_result_schema '{iso standard 10303 part(62) version(1) object(1) product_data_equivalence_inspection_result_schema(1)}';

  REFERENCE FROM measure_schema
    (count_measure,
     measure_with_unit);

  REFERENCE FROM product_data_equivalence_criteria_schema
    (data_equivalence_criteria_representation,
     data_equivalence_criterion,
     data_equivalence_inspection_requirement,
     summary_report_style_type);
    
  REFERENCE FROM representation_schema
    (representation,
     representation_item,
     representation_item_relationship);

  REFERENCE FROM support_resource_schema 
    (label,
     text,
     bag_to_set);

  TYPE inspected_equivalence_element_select = EXTENSIBLE GENERIC_ENTITY SELECT;
  END_TYPE;
  
  ENTITY criterion_report_item_with_number_of_instances
    SUBTYPE OF(data_equivalence_inspection_criterion_report_item);
      statistical_value : count_measure;
      value_type        : summary_report_style_type;
    UNIQUE
      UR1: SELF\data_equivalence_inspection_criterion_report_item.criterion_report,value_type;
  END_ENTITY;

  ENTITY criterion_report_item_with_value
    SUBTYPE OF(data_equivalence_inspection_criterion_report_item);
      report_value : measure_with_unit;
      value_type        : label;
    UNIQUE
      UR1: SELF\data_equivalence_inspection_criterion_report_item.criterion_report,value_type;
  END_ENTITY;

  ENTITY data_equivalence_inspected_element_pair
    SUBTYPE OF(representation_item);
     comparing_elements : SET [1:?] OF inspected_equivalence_element_select;
     compared_elements : SET [1:?] OF inspected_equivalence_element_select;
    WHERE
      WR1 : SIZEOF(QUERY(q <* bag_to_set( USEDIN(SELF,
                            'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
                          |'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
                           'DATA_EQUIVALENCE_CRITERIA_REPRESENTATION'
                           IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_inspection_criterion_report
    SUBTYPE OF(data_equivalence_inspection_report);
      statistical_values : SET [1:?] OF data_equivalence_inspection_criterion_report_item;
  END_ENTITY;

  ENTITY data_equivalence_inspection_criterion_report_item
    ABSTRACT SUPERTYPE OF (ONEOF(criterion_report_item_with_number_of_instances,
                                 criterion_report_item_with_value))
    SUBTYPE OF(representation_item);
    INVERSE
      criterion_report : data_equivalence_inspection_criterion_report FOR statistical_values;
    WHERE
      WR1 : SIZEOF(QUERY(q <* bag_to_set( USEDIN(SELF,
                            'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
                          |'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
                           'DATA_EQUIVALENCE_CRITERIA_REPRESENTATION'
                           IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_inspection_instance_report
    SUBTYPE OF(data_equivalence_inspection_report);
      inspected_instances : LIST [1:?] OF data_equivalence_inspection_instance_report_item;
  END_ENTITY;

  ENTITY data_equivalence_inspection_instance_report_item
    SUBTYPE OF(representation_item);
     inspected_element : data_equivalence_inspected_element_pair;
    WHERE
      WR1 : SIZEOF(QUERY(q <* bag_to_set( USEDIN(SELF,
                            'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
                          |'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
                           'DATA_EQUIVALENCE_CRITERIA_REPRESENTATION'
                           IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_inspection_report
    ABSTRACT SUPERTYPE OF (ONEOF(data_equivalence_inspection_criterion_report, 
                                 data_equivalence_inspection_instance_report))
    SUBTYPE OF(representation_item);
      inspection_result : data_equivalence_inspection_result;
    WHERE
      WR1 : SIZEOF(QUERY(q <* bag_to_set( USEDIN(SELF,
                            'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
                          |'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
                           'DATA_EQUIVALENCE_CRITERIA_REPRESENTATION'
                           IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_inspection_result
    SUBTYPE OF(representation_item);
      criterion_inspected : data_equivalence_criterion;
    WHERE
      WR1 : SIZEOF(QUERY(q <* bag_to_set( USEDIN(SELF,
                            'REPRESENTATION_SCHEMA.REPRESENTATION.ITEMS'))
                          |'PRODUCT_DATA_EQUIVALENCE_CRITERIA_SCHEMA.'+
                           'DATA_EQUIVALENCE_CRITERIA_REPRESENTATION'
                           IN TYPEOF(q)))=0;
  END_ENTITY;

  ENTITY data_equivalence_inspection_result_representation
    SUBTYPE OF(representation);
    criteria_inspected: data_equivalence_criteria_representation;
    WHERE
      WR1 : SIZEOF( QUERY( q <* SELF\representation.items|
                                'PRODUCT_DATA_EQUIVALENCE_INSPECTION_RESULT_SCHEMA.' +
                                'DATA_EQUIVALENCE_INSPECTION_RESULT' IN TYPEOF(q))) > 0;
  END_ENTITY;

  ENTITY data_equivalence_inspection_result_with_judgement
    SUBTYPE OF(data_equivalence_inspection_result);
      judgement : BOOLEAN;
  END_ENTITY;

  ENTITY data_equivalence_report_inspection_association
    SUBTYPE OF(representation_item_relationship);
      SELF\representation_item_relationship.relating_representation_item : data_equivalence_inspection_requirement;
      SELF\representation_item_relationship.related_representation_item  : data_equivalence_inspection_report;
  END_ENTITY;

END_SCHEMA; -- product_data_equivalence_inspection_result_schema
